services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: elysia-ontime:prod
    container_name: ontime-app-prod
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: "3081"
      COOKIE_SECURE: "false"
    network_mode: host
