services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: ontime-app:latest
    container_name: ontime-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "3080"
      COOKIE_SECURE: "true"
      FORCE_HTTPS: "true"
    network_mode: host
