import { type FormEvent, useState } from 'react';

type Language = 'fr' | 'en';
type User = { id: string; email: string; firstName: string; lastName: string };
type Props = { language: Language; user: User; onUserChange: (user: User) => void; onLanguageChange: (value: Language) => void; onLogout: () => Promise<void>; onNavigateWorkLog: () => void; onNavigateClients: () => void; onNavigateProjects: () => void };
const copy = {
  fr: { journal: 'Journal', clients: 'Mes clients', projects: 'Projets', profile: 'Profil', logout: 'Se déconnecter', title: 'Mon profil', subtitle: 'Gérez vos renseignements et la sécurité de votre compte.', info: 'Renseignements personnels', firstName: 'Prénom', lastName: 'Nom', email: 'Adresse courriel', save: 'Enregistrer les modifications', saved: 'Profil mis à jour.', password: 'Changer le mot de passe', current: 'Mot de passe actuel', next: 'Nouveau mot de passe', confirm: 'Confirmer le nouveau mot de passe', change: 'Changer le mot de passe', changed: 'Mot de passe modifié.', mismatch: 'Les nouveaux mots de passe ne correspondent pas.', invalid: 'Le mot de passe actuel est incorrect.', duplicate: 'Cette adresse courriel est déjà utilisée.', required: 'Tous les champs sont obligatoires.', error: 'Une erreur est survenue.' },
  en: { journal: 'Work log', clients: 'My clients', projects: 'Projects', profile: 'Profile', logout: 'Sign out', title: 'My profile', subtitle: 'Manage your information and account security.', info: 'Personal information', firstName: 'First name', lastName: 'Last name', email: 'Email address', save: 'Save changes', saved: 'Profile updated.', password: 'Change password', current: 'Current password', next: 'New password', confirm: 'Confirm new password', change: 'Change password', changed: 'Password changed.', mismatch: 'New passwords do not match.', invalid: 'Current password is incorrect.', duplicate: 'This email address is already in use.', required: 'All fields are required.', error: 'Something went wrong.' },
} as const;

export function ProfilePage({ language, user, onUserChange, onLanguageChange, onLogout, onNavigateWorkLog, onNavigateClients, onNavigateProjects }: Props) {
  const text = copy[language]; const [firstName, setFirstName] = useState(user.firstName); const [lastName, setLastName] = useState(user.lastName); const [email, setEmail] = useState(user.email); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [profileMessage, setProfileMessage] = useState(''); const [passwordMessage, setPasswordMessage] = useState(''); const [saving, setSaving] = useState(false);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); setProfileMessage(''); if (!firstName.trim() || !lastName.trim() || !email.trim()) { setProfileMessage(text.required); return; } setSaving(true); try { const response = await fetch('/api/auth/profile', { method: 'PATCH', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ firstName: firstName.trim(), lastName: lastName.trim(), email: email.trim() }) }); const payload = await response.json() as { user?: User; error?: string }; if (!response.ok) setProfileMessage(payload.error === 'EMAIL_EXISTS' ? text.duplicate : text.error); else if (payload.user) { onUserChange(payload.user); setProfileMessage(text.saved); } } catch { setProfileMessage(text.error); } finally { setSaving(false); } };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); setPasswordMessage(''); if (newPassword !== confirmation) { setPasswordMessage(text.mismatch); return; } setSaving(true); try { const response = await fetch('/api/auth/change-password', { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ currentPassword, newPassword }) }); const payload = await response.json() as { error?: string }; if (!response.ok) setPasswordMessage(payload.error === 'INVALID_CURRENT_PASSWORD' ? text.invalid : text.error); else { setCurrentPassword(''); setNewPassword(''); setConfirmation(''); setPasswordMessage(text.changed); } } catch { setPasswordMessage(text.error); } finally { setSaving(false); } };
  return <main className="app-page"><header className="app-header"><div className="app-brand"><span className="brand-mark">OT</span><span>OnTime</span></div><nav className="app-nav"><button onClick={onNavigateWorkLog}>{text.journal}</button><button onClick={onNavigateClients}>{text.clients}</button><button onClick={onNavigateProjects}>{text.projects}</button><button className="active">{text.profile}</button></nav><div className="header-actions"><div className="language-switch compact">{(['fr','en'] as const).map((value) => <button key={value} className={language === value ? 'active' : ''} onClick={() => onLanguageChange(value)}>{value.toUpperCase()}</button>)}</div><div className="user-chip"><span>{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><button onClick={() => void onLogout()}>{text.logout}</button></div></div></div></header><section className="content-shell profile-shell"><div className="page-heading"><div><p className="eyebrow">ONTIME</p><h1>{text.title}</h1><p>{text.subtitle}</p></div></div><div className="profile-grid"><section className="profile-card"><h2>{text.info}</h2><form onSubmit={saveProfile}><label>{text.firstName}<input value={firstName} onChange={(event) => setFirstName(event.target.value)} maxLength={100} /></label><label>{text.lastName}<input value={lastName} onChange={(event) => setLastName(event.target.value)} maxLength={100} /></label><label>{text.email}<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} maxLength={320} /></label>{profileMessage ? <p className={profileMessage === text.saved ? 'success-message' : 'error-message'}>{profileMessage}</p> : null}<button className="primary-button" disabled={saving}>{text.save}</button></form></section><section className="profile-card"><h2>{text.password}</h2><form onSubmit={savePassword}><label>{text.current}<input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} minLength={8} autoComplete="current-password" /></label><label>{text.next}<input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} autoComplete="new-password" /></label><label>{text.confirm}<input type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} minLength={8} autoComplete="new-password" /></label>{passwordMessage ? <p className={passwordMessage === text.changed ? 'success-message' : 'error-message'}>{passwordMessage}</p> : null}<button className="primary-button" disabled={saving || currentPassword.length < 8 || newPassword.length < 8 || confirmation.length < 8}>{text.change}</button></form></section></div></section></main>;
}
