import { type FormEvent, useEffect, useMemo, useState } from 'react';

type Language = 'fr' | 'en';
type User = { firstName: string; lastName: string };
type Client = { id: string; name: string; isActive: boolean };
type Project = { id: string; name: string; isActive: boolean };
type Entry = { id: string; clientName: string; projectName: string; workDate: string; durationMinutes: number; description: string; hourlyRate: string; amount: string; isBilled: boolean; isDeleted: boolean };
type Preset = 'day' | 'week' | 'month' | 'year' | 'custom';
type Sort = 'workDate' | 'client' | 'project' | 'duration' | 'hourlyRate' | 'amount' | 'isBilled';
type Props = { language: Language; user: User; onLanguageChange: (value: Language) => void; onLogout: () => Promise<void>; onNavigateClients: () => void; onNavigateProjects: () => void; onNavigateProfile: () => void };

const pad = (value: number) => String(value).padStart(2, '0');
const iso = (date: Date) => `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
const period = (preset: Preset, anchor: Date) => {
  const from = new Date(anchor); const to = new Date(anchor);
  if (preset === 'week') { const offset = (anchor.getDay() + 1) % 7; from.setDate(anchor.getDate() - offset); to.setTime(from.getTime()); to.setDate(from.getDate() + 6); }
  if (preset === 'month') { from.setDate(1); to.setMonth(anchor.getMonth() + 1, 0); }
  if (preset === 'year') { from.setMonth(0, 1); to.setMonth(11, 31); }
  return { from: iso(from), to: iso(to) };
};
const formatDate = (value: string) => { const [y, m, d] = value.split('-'); return `${d}/${m}/${y}`; };
const formatDuration = (minutes: number) => `${pad(Math.floor(minutes / 60))}:${pad(minutes % 60)}`;
const pageSizeCookie = () => Number(document.cookie.match(/(?:^|; )ontime_page_size=(10|25|50|100)/)?.[1] ?? 50);

const copy = {
  fr: { journal: 'Journal', clients: 'Mes clients', projects: 'Projets', logout: 'Se déconnecter', title: 'Journal de travail', day: 'Jour', week: 'Semaine', month: 'Mois', year: 'Année', custom: 'Personnalisé', from: 'Du', to: 'Au', allClients: 'Tous les clients', allProjects: 'Tous les projets', client: 'Client', project: 'Projet', add: 'Nouvelle entrée', export: 'Exporter Excel', date: 'Date', description: 'Description', hours: 'Heures', rate: 'Taux', value: 'Valeur', billed: 'Facturé', items: 'Entrées', confidential: 'Confidentiel', deleted: 'Afficher les supprimées', edit: 'Modifier', duplicate: 'Copier', next: 'Copier au prochain jour ouvrable', toggleBilled: 'Inverser facturation', toggleDeleted: 'Masquer / restaurer', empty: 'Aucune entrée pour ces filtres.', selectProject: 'Sélectionnez un client et un projet précis pour ajouter une entrée.', newEntry: 'Nouvelle entrée', editEntry: 'Modifier l’entrée', back: 'Retour', save: 'Valider', duration: 'Durée (HH:MM)', required: 'La description est obligatoire et la durée doit être un multiple de 15 minutes.', warning: 'Cette entrée est facturée. Voulez-vous vraiment continuer?', confirmDelete: 'Inverser le statut supprimé des entrées sélectionnées?', error: 'Une erreur est survenue.', page: 'Page', previous: 'Précédente', following: 'Suivante' },
  en: { journal: 'Work log', clients: 'My clients', projects: 'Projects', logout: 'Sign out', title: 'Work log', day: 'Day', week: 'Week', month: 'Month', year: 'Year', custom: 'Custom', from: 'From', to: 'To', allClients: 'All clients', allProjects: 'All projects', client: 'Client', project: 'Project', add: 'New entry', export: 'Export Excel', date: 'Date', description: 'Description', hours: 'Hours', rate: 'Rate', value: 'Value', billed: 'Billed', items: 'Entries', confidential: 'Confidential', deleted: 'Show deleted', edit: 'Edit', duplicate: 'Copy', next: 'Copy to next business day', toggleBilled: 'Toggle billed', toggleDeleted: 'Hide / restore', empty: 'No entries match these filters.', selectProject: 'Select one client and one project to add an entry.', newEntry: 'New entry', editEntry: 'Edit entry', back: 'Back', save: 'Save', duration: 'Duration (HH:MM)', required: 'Description is required and duration must be a multiple of 15 minutes.', warning: 'This entry is billed. Do you really want to continue?', confirmDelete: 'Toggle deleted status for selected entries?', error: 'Something went wrong.', page: 'Page', previous: 'Previous', following: 'Next' },
} as const;

export function WorkLogPage(props: Props) {
  const { language, user, onLanguageChange, onLogout, onNavigateClients, onNavigateProjects, onNavigateProfile } = props;
  const text = copy[language]; const today = useMemo(() => new Date(), []); const initial = period('month', today);
  const [preset, setPreset] = useState<Preset>('month'); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to);
  const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(''); const [projects, setProjects] = useState<Project[]>([]); const [projectId, setProjectId] = useState('');
  const [entries, setEntries] = useState<Entry[]>([]); const [selected, setSelected] = useState<string[]>([]); const [summary, setSummary] = useState({ itemCount: 0, totalMinutes: 0, totalAmount: '0.00' });
  const [includeDeleted, setIncludeDeleted] = useState(false); const [confidential, setConfidential] = useState(document.cookie.includes('ontime_confidential=true')); const [pageSize, setPageSize] = useState(pageSizeCookie); const [page, setPage] = useState(1); const [pageCount, setPageCount] = useState(1); const [sortBy, setSortBy] = useState<Sort>('workDate'); const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc'); const [reload, setReload] = useState(0);
  const [editing, setEditing] = useState<Entry | null>(null); const [formOpen, setFormOpen] = useState(false); const [workDate, setWorkDate] = useState(iso(today)); const [time, setTime] = useState('08:00'); const [description, setDescription] = useState(''); const [error, setError] = useState('');

  useEffect(() => { void fetch('/api/clients', { credentials: 'include' }).then((response) => response.json()).then((data: { clients: Client[] }) => setClients(data.clients.filter((item) => item.isActive))).catch(() => setError(text.error)); }, []);
  useEffect(() => { setProjectId(''); if (!clientId) { setProjects([]); return; } void fetch(`/api/projects?clientId=${clientId}`, { credentials: 'include' }).then((response) => response.json()).then((data: { projects: Project[] }) => setProjects(data.projects.filter((item) => item.isActive))).catch(() => setError(text.error)); }, [clientId]);
  useEffect(() => {
    const params = new URLSearchParams({ from, to, includeDeleted: String(includeDeleted), page: String(page), pageSize: String(pageSize), sortBy, sortDirection });
    if (clientId) params.set('clientId', clientId); if (projectId) params.set('projectId', projectId);
    void fetch(`/api/work-entries?${params}`, { credentials: 'include' }).then(async (response) => { if (!response.ok) throw new Error(); return response.json(); }).then((data: { entries: Entry[]; summary: typeof summary; pageCount: number }) => { setEntries(data.entries); setSummary(data.summary); setPageCount(data.pageCount); setSelected([]); }).catch(() => setError(text.error));
  }, [from, to, clientId, projectId, includeDeleted, page, pageSize, sortBy, sortDirection, reload]);

  const choosePreset = (value: Preset) => { setPreset(value); setPage(1); if (value !== 'custom') { const range = period(value, today); setFrom(range.from); setTo(range.to); } };
  const sort = (value: Sort) => { if (sortBy === value) setSortDirection((current) => current === 'asc' ? 'desc' : 'asc'); else { setSortBy(value); setSortDirection('asc'); } };
  const openCreate = () => { setEditing(null); setWorkDate(iso(today)); setTime('08:00'); setDescription(''); setError(''); setFormOpen(true); };
  const openEdit = (entry: Entry) => { if (entry.isBilled && !confirm(text.warning)) return; setEditing(entry); setWorkDate(entry.workDate); setTime(formatDuration(entry.durationMinutes)); setDescription(entry.description); setError(''); setFormOpen(true); };
  const minutes = () => { const match = /^(\d+):([0-5]\d)$/.exec(time); return match ? Number(match[1]) * 60 + Number(match[2]) : 0; };
  const save = async (event: FormEvent) => { event.preventDefault(); const durationMinutes = minutes(); if (!description.trim() || durationMinutes < 15 || durationMinutes % 15) { setError(text.required); return; } const response = await fetch(editing ? `/api/work-entries/${editing.id}` : '/api/work-entries', { method: editing ? 'PATCH' : 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...(!editing ? { projectId } : {}), workDate, durationMinutes, description: description.trim() }) }); if (!response.ok) { setError(text.error); return; } setFormOpen(false); setReload((current) => current + 1); };
  const action = async (path: string, body: unknown) => { const response = await fetch(path, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) setError(text.error); else setReload((current) => current + 1); };
  const exportExcel = async () => { const params = new URLSearchParams({ from, to, includeDeleted: String(includeDeleted), confidential: String(confidential), language }); if (clientId) params.set('clientId', clientId); if (projectId) params.set('projectId', projectId); const response = await fetch(`/api/work-entries/export?${params}`, { credentials: 'include' }); if (!response.ok) { setError(text.error); return; } const blob = await response.blob(); const disposition = response.headers.get('content-disposition') ?? ''; const name = disposition.match(/filename="([^"]+)"/)?.[1] ?? 'OnTime.xlsx'; const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = name; link.click(); URL.revokeObjectURL(link.href); };
  const columns = !clientId ? 'both' : !projectId ? 'project' : 'none';

  return <main className="app-page"><header className="app-header"><div className="app-brand"><span className="brand-mark">OT</span><span>OnTime</span></div><nav className="app-nav"><button className="active">{text.journal}</button><button onClick={onNavigateClients}>{text.clients}</button><button onClick={onNavigateProjects}>{text.projects}</button><button onClick={onNavigateProfile}>{language === 'fr' ? 'Profil' : 'Profile'}</button></nav><div className="header-actions"><label className="confidential-switch"><input type="checkbox" checked={confidential} onChange={(event) => { setConfidential(event.target.checked); document.cookie = `ontime_confidential=${event.target.checked}; Max-Age=31536000; Path=/; SameSite=Lax`; }} />{text.confidential}</label><div className="language-switch compact">{(['fr', 'en'] as const).map((value) => <button key={value} className={language === value ? 'active' : ''} onClick={() => onLanguageChange(value)}>{value.toUpperCase()}</button>)}</div><div className="user-chip"><span>{user.firstName[0]}{user.lastName[0]}</span><div><strong>{user.firstName} {user.lastName}</strong><button onClick={() => void onLogout()}>{text.logout}</button></div></div></div></header>
    <section className="content-shell worklog-shell"><div className="page-heading"><div><p className="eyebrow">ONTIME</p><h1>{text.title}</h1></div><div className="heading-actions"><button className="secondary-button export-button" onClick={() => void exportExcel()}>{text.export}</button><button className="add-button" disabled={!projectId} onClick={openCreate}><span>+</span>{text.add}</button></div></div>
      <div className="journal-filters"><div className="preset-group">{(['day', 'week', 'month', 'year', 'custom'] as Preset[]).map((value) => <button className={preset === value ? 'active' : ''} onClick={() => choosePreset(value)} key={value}>{text[value]}</button>)}</div><label>{text.from}<input type="date" value={from} onChange={(event) => { setPreset('custom'); setFrom(event.target.value); setPage(1); }} /></label><label>{text.to}<input type="date" value={to} onChange={(event) => { setPreset('custom'); setTo(event.target.value); setPage(1); }} /></label><label>{text.client}<select value={clientId} onChange={(event) => { setClientId(event.target.value); setPage(1); }}><option value="">{text.allClients}</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{text.project}<select disabled={!clientId} value={projectId} onChange={(event) => { setProjectId(event.target.value); setPage(1); }}><option value="">{text.allProjects}</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
      {!projectId ? <p className="journal-hint">{text.selectProject}</p> : null}{error ? <p className="error-message page-error">{error}</p> : null}
      <div className="journal-summary"><div><span>{text.items}</span><strong>{summary.itemCount}</strong></div><div><span>{text.hours}</span><strong>{formatDuration(Number(summary.totalMinutes))}</strong></div>{!confidential ? <div><span>{text.value}</span><strong>${Number(summary.totalAmount).toLocaleString('en-CA', { minimumFractionDigits: 2 })}</strong></div> : null}<label><input type="checkbox" checked={includeDeleted} onChange={(event) => { setIncludeDeleted(event.target.checked); setPage(1); }} />{text.deleted}</label></div>
      <div className="journal-actions"><button disabled={!selected.length} onClick={() => void action('/api/work-entries/toggle-billed', { ids: selected })}>{text.toggleBilled}</button><button disabled={!selected.length} className="danger" onClick={() => { if (confirm(text.confirmDelete)) void action('/api/work-entries/toggle-deleted', { ids: selected }); }}>{text.toggleDeleted}</button></div>
      <div className="journal-table-wrap"><table className="journal-table"><thead><tr><th><input type="checkbox" checked={entries.length > 0 && selected.length === entries.length} onChange={(event) => setSelected(event.target.checked ? entries.map((item) => item.id) : [])} /></th>{columns === 'both' ? <th onClick={() => sort('client')}>{text.client}</th> : null}{columns !== 'none' ? <th onClick={() => sort('project')}>{text.project}</th> : null}<th onClick={() => sort('workDate')}>{text.date}</th><th>{text.description}</th><th onClick={() => sort('duration')}>{text.hours}</th>{!confidential ? <><th onClick={() => sort('hourlyRate')}>{text.rate}</th><th onClick={() => sort('amount')}>{text.value}</th></> : null}<th onClick={() => sort('isBilled')}>{text.billed}</th><th /></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id} className={entry.isDeleted ? 'deleted-entry' : ''}><td><input type="checkbox" checked={selected.includes(entry.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, entry.id] : current.filter((id) => id !== entry.id))} /></td>{columns === 'both' ? <td>{entry.clientName}</td> : null}{columns !== 'none' ? <td>{entry.projectName}</td> : null}<td>{formatDate(entry.workDate)}</td><td className="description-cell">{entry.description}</td><td>{formatDuration(entry.durationMinutes)}</td>{!confidential ? <><td>${Number(entry.hourlyRate).toFixed(2)}</td><td>${Number(entry.amount).toFixed(2)}</td></> : null}<td><input type="checkbox" checked={entry.isBilled} readOnly /></td><td className="row-actions"><button title={text.edit} onClick={() => openEdit(entry)}>✎</button><button title={text.duplicate} onClick={() => void action(`/api/work-entries/${entry.id}/duplicate`, { nextWorkday: false })}>⧉</button><button title={text.next} onClick={() => void action(`/api/work-entries/${entry.id}/duplicate`, { nextWorkday: true })}>⧉+1</button></td></tr>)}{!entries.length ? <tr><td colSpan={12} className="empty-table">{text.empty}</td></tr> : null}</tbody></table></div>
      <div className="journal-pagination"><label>{text.items}<select value={pageSize} onChange={(event) => { const value = Number(event.target.value); setPageSize(value); setPage(1); document.cookie = `ontime_page_size=${value}; Max-Age=31536000; Path=/; SameSite=Lax`; }}>{[10, 25, 50, 100].map((value) => <option key={value}>{value}</option>)}</select></label><button disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>{text.previous}</button><span>{text.page} {page} / {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage((current) => current + 1)}>{text.following}</button></div>
    </section>
    {formOpen ? <div className="modal-backdrop"><section className="client-modal entry-modal"><div className="modal-heading"><h2>{editing ? text.editEntry : text.newEntry}</h2><button className="close-button" onClick={() => setFormOpen(false)}>×</button></div><form onSubmit={save}><label>{text.date}<input type="date" value={workDate} onChange={(event) => setWorkDate(event.target.value)} required /></label><label>{text.duration}<input value={time} onChange={(event) => setTime(event.target.value)} placeholder="08:00" required /></label><label>{text.description}<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={10} required /></label>{error ? <p className="error-message">{error}</p> : null}<div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setFormOpen(false)}>{text.back}</button><button className="primary-button">{text.save}</button></div></form></section></div> : null}
  </main>;
}
